spring.application.name=gateway-service

server.port=${SERVER_PORT:8080}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring.cloud.gateway.server.webmvc.discovery.locator.enabled=false

management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=${HEALTH_SHOW_DETAILS:NEVER}

spring.cloud.gateway.server.webmvc.routes[0].id=identity-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://IDENTITY-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=identity-user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://IDENTITY-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webmvc.routes[2].id=commerce-catalog-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://COMMERCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/catalog/**

spring.cloud.gateway.server.webmvc.routes[3].id=commerce-cart-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://COMMERCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/cart/**

spring.cloud.gateway.server.webmvc.routes[4].id=commerce-order-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://COMMERCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/orders/**

spring.cloud.gateway.server.webmvc.routes[5].id=commerce-payment-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://COMMERCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/payments/**

spring.cloud.gateway.server.webmvc.routes[6].id=commerce-audit-service
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://COMMERCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/v1/audit/**

spring.cloud.gateway.server.webmvc.routes[7].id=agent-service
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://AGENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/v1/agent/**